defaults:
  - data: shakespeare
  - model: gpt_small
  - optimizer: adamw

run:
  validate:
    validate_interval: 500
    eval_iters: 50
  checkpoint:
    checkpoint_interval: 500
  iterations: 5000

device: available # choice of available or directly set (cpu | cuda | mps)
save_final: True

hydra:
  job:
    chdir: True
